# APP
homepage:
  path: /
  controller: App\Controller\AppController::homepage


# ROLES
role_sort:
  path: /roles
  controller: App\Controller\RoleController::sort


# PARTIES
party_lobby:
  path: /parties
  controller: App\Controller\PartyController::lobby

party_new:
  path: /parties/new
  controller: App\Controller\PartyController::new

party_show:
  path: /parties/{id<[0-9]+>}
  controller: App\Controller\PartyController::show

party_stats:
  path: /parties/stats
  controller: App\Controller\PartyController::stats



# ACCOUNTS
account_connection:
  path: /account/connection
  controller: App\Controller\AccountController::connection

account_logout:
  path: /account/logout
  controller: App\Controller\AccountController::logout